### ISSUE TITLE
Use multiple threads to increase performance

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge-creator#10]
Allow using [multiple threads](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#advanced-options-only-use-when-you-know-what-you-are-doing) to increase performance via configuration variable.

**Comment by boldtrn** [comment]
Nice feature! Maybe it would make sense to make the threads definable on a per map base. Maybe it would be a good idea to have multiple threads for smaller maps, but only one thread for larger maps?

**Comment by devemux86** [comment]
That makes sense, we just need to hande properly the possible many optional command args.

**Comment by devemux86** [comment]
There is the base implementation, further enhancement can be examined in the future.
