### ISSUE TITLE
v4 map builds: add languages for each region

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge-creator#15]
For the multilingual builds we should be adding the local language(s) for each region, for Italy Italian etc pp.

**Comment by devemux86** [comment]
Multilingual maps have always the default (local) language in them and then added the declared ones (can see also [map-writer documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#basic-options)).

It'd be nice to have specific languages per country, like OpenAndroMaps does.
Creator already supports it, though still a significant effort to collect all of them.

**Comment by devemux86** [comment]
Local language always exists, so more fine tuning can be examined in the future.
