### ISSUE TITLE
Write map file to $DATA area

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge-creator#19]
I think it is better to write the output file to the $DATA and not to the $MAPS area. 

The $MAPS area is visible to external users and might be picked up be mirrors, where a half-finished file could stay for until the next sync.

**Comment by devemux86** [comment]
The maps and pois areas are supposed to be just the output folders, not visible by users.
On each server implementation can't the administrator move the results to the public folders?

**Comment by devemux86** [comment]
> On each server implementation can't the administrator move the results to the public folders?

If move maps, then cannot do date / size compare.
So an intermediate solution indeed could be useful.

**Comment by ludwigb** [comment]
It is actually difficult to know when a map file has been completed. 
I noticed this problem when running rsync to copy the $MAPS are to the publicly visible area. A simple rsync will just copy all the files, even half-completed ones. 
(Of course I can match on the file name that it does not have a "-2" in it)

**Comment by devemux86** [comment]
And that would allow also to keep old maps & pois in case of failed creation without overwrite.
I'll make the changes later.

**Comment by devemux86** [comment]
Now the maps & pois are created first in work dir.
Then checks are made and if ok, are moved in "public" dirs.
