### ISSUE TITLE
Separate $DATA area by version

### ISSUE THREAD

**Issue by ludwigb** [mapsforge/mapsforge-creator#20]
The $DATA area should also be segmented, like the $MAPS area, by version (v3 etc).

This ensures that, if v3 and v4 scripts are run in parallel, they do not overwrite each other.

**Comment by devemux86** [comment]
That means duplicate intermediate data, which is not any small size.
If ok with that, then can be solved also by having multiple mapsforge-creator configurations.
Each one with different environment variables for the various paths and can run in parallel?

**Comment by ludwigb** [comment]
I would suggest deleting the intermediate data once a map has been generated. 

Your suggestion is also feasible, I did not think of it.

**Comment by devemux86** [comment]
Do you think we still need separate work area per map version or could better handle it via separate environment variables?

**Comment by devemux86** [comment]
Closing since there is solution with different configurations and for not mixing with poi creation too.
