### ISSUE TITLE
Use https for Geofabrik?

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#21]
Geofabrik offers https for downloading files. Probably download speed will be lower with https? Not sure if we should do this or not.

**Comment by devemux86** [comment]
Probably on first packets for the connection to initialize, then shouldn't be a problem(?).

All http can be changed with https in the script supported.

**Comment by boldtrn** [comment]
> then shouldn't be a problem(?)

Packets are encrypted and need to be decrypted, so it can never be as performant as unencrypted traffic.

I have seen some 404 issues with Geofabrik recently and was wondering if switching to https might fix these issues.

**Comment by devemux86** [comment]
Download speed normally shouldn't worry us, map creation takes much longer. :slightly_smiling_face:

**Comment by boldtrn** [comment]
I agree, also https has many benefits, so I think we should at least try it :).
