### ISSUE TITLE
Specify path to GraphHopper config

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#27]
It's nice that we can build graphs with the mapsforge-creator now as well. I just gave this a try and saw that I can't specify a path to the GraphHopper config, it is assumed that it is in the same directory as the gh.jar. Wouldn't it make sense to be able to separate the two?

**Comment by devemux86** [comment]
Generally I prefer to not complicate the creator script with too many extra variables for each new build process (map / poi / graph) unless it's absolutely necessary.

What is the problem or difficulties with current approach?
`GRAPHHOPPER_HOME` holds everything GraphHopper related tidy in one place, like `OSMOSIS_HOME` specifies similarly the dir holding all Osmosis related stuff.

It's nice that GraphHopper can provide now a single jar with dependencies, the old days we had to have a folder with all needed jars, so a generic folder is a future proof approach too.

_By the way let's make such discussions in the [forum](https://groups.google.com/group/mapsforge-dev) first and if there is need can create issues for features that are agreed to be implemented._

**Comment by boldtrn** [comment]
It separates the executable part from the configurable part. I don't place my config files in /bin :).

The osmosis configs like the `MAP_TRANSFORM_FILE` can be placed in a different directory as well. It just makes sense to have these things separate IMHO.

**Comment by devemux86** [comment]
> It separates the executable part from the configurable part. I don't place my config files in /bin :).

What do you mean?
There isn't anything to put in any bin.
Just create a graphhopper folder (e.g. in home), place inside the latest release's jar and config and are ready to generate graphs.

**Comment by devemux86** [comment]
In such a workflow then a `GRAPHHOPPER_HOME` has no real meaning.
Can include instead separate variables for the graphhopper jar and it config file.

**Comment by boldtrn** [comment]
> There isn't anything to put in any bin.

The GraphHopper folder is like a bin, it should contain just an executable jar and should be a different folder than the config. This is true even for the default GraphHopper, where the executeable jar lives in the target folder. 

> In such a workflow then GRAPHHOPPER_HOME has no real meaning.

Yes, it would be probably better to specify the location of the GraphHopper jar, this would make versioning easier as well probably.

Feel free to close this issue if you don't like it. It makes configuring GraphHopper a bit messy though, because I keep the config separate from the executable and have to copy it to the GraphHopper folder.

**Comment by devemux86** [comment]
I need to make some tests and see for a simple implementation without much confusion for the users. GraphHopper versioning would be an added benefit.

**Comment by devemux86** [comment]
I pushed the GraphHopper jar / config variables separation.

**Comment by boldtrn** [comment]
Awesome, that's great, thank you!
