### ISSUE TITLE
Zip is required

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#29]
We should add to the documentation that you have to install zip (e.g.`apt-get install zip`). This is not installed by default on every distro.

**Comment by devemux86** [comment]
> This is not installed by default on every distro.

Really? And how they handle the most common archive format then?

**Comment by devemux86** [comment]
I updated the README.

**Comment by boldtrn** [comment]
> I updated the README.

Thanks :)

> Really?

At least it was not installed on my ubuntu-minimal. On regular full desktop installations this might be added by default.
