### ISSUE TITLE
Fail, if there was an issue

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#3]
Currently the script does not fail, if any of the commands fail. If anything fails, we should exit the script with an error code (e.g. 1), so we should check every execution and call `exit 1` if it fails. This makes it easier to check if the overall script worked or not

**Comment by devemux86** [comment]
Indeed that would be a nice improvement.

**Comment by devemux86** [comment]
Closing as most important commands seem to be handled.
