### ISSUE TITLE
Allow adding other sources than Geofabrik

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#4]
As mentioned by Ludwig [here](https://groups.google.com/d/msg/mapsforge-dev/AHl1lRpFRCg/aMtVGIZiBAAJ):
I also think that this should be more flexible in the sense that other sources should be allowed more easily. The main rationale for this is to allow others to hook in their extracts (or custom generated data sources). This would not only be for their benefits, but also for ours: the more the scripts get used by others, the more input we will get in terms of bug fixes, improvements (maybe wishful thinking).

**Comment by devemux86** [comment]
Probably have separate scripts (even calling each other), in order to avoid one complicated script and for easier maintenance.

**Comment by devemux86** [comment]
Probably in the future if there is interest for some contribution.
