### ISSUE TITLE
Automatically update/download the coastlines

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#5]
As mentioned by Ludwig [here](https://groups.google.com/d/msg/mapsforge-dev/AHl1lRpFRCg/aMtVGIZiBAAJ):
There also needs to be something that refreshes the coastline files. They do change a bit and should really be in sync as much as possible. Before I run a batch on our server, I delete the input files, forcing our current script to get the coastlines again.

**Comment by devemux86** [comment]
That would a nice (and easy) addition.

**Comment by ludwigb** [comment]
A solution might be to have a script that get executed before inside the map-creator command and checks if the coastlines exist and if so if are older than the usual time limit. 
That keeps maps and coastlines in sync.

**Comment by devemux86** [comment]
Thanks, that seems the simplest solution.

**Comment by devemux86** [comment]
I pushed the automatic land polygons download or update, depending on days check.
