### ISSUE TITLE
Skip map generation if map exists and is newer than X days

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#6]
As mentioned by Ludwig [here](https://groups.google.com/d/msg/mapsforge-dev/AHl1lRpFRCg/aMtVGIZiBAAJ):
Something else we put in place was to check the date of files when to regenerate something. This has been useful to rerun the whole script if errors occurred to speed the regeneration of files up that were corrupted. 

So it would be nice if we could make the time range configurable so that the script can skip the map if the source map is younger than some time-range.

**Comment by devemux86** [comment]
Bash can probably provide such functionality.

**Comment by boldtrn** [comment]
This could be doable with [this](https://stackoverflow.com/a/32019461/1548788) command:
```
if [[ $(find "$filename" -mtime +100 -print) ]]; then
  echo "File $filename exists and is older than 100 days"
fi
``` 

Before that we would probably have to check if the file exists, which could be doable like [this](https://stackoverflow.com/a/638980/1548788):
```
if [ ! -f /tmp/foo.txt ]; then
    echo "File not found!"
fi
```

**Comment by devemux86** [comment]
Thanks for the hints!
I pushed an implementation to exit early (need special code?) if file exists and is newer than 30 days (as in old creator).
@boldtrn can you check if all work ok?

**Comment by devemux86** [comment]
I added parameters to make map check and days configurable.

**Comment by boldtrn** [comment]
Awesome, this looks good. Will give it a try over the next couple of days.

**Comment by boldtrn** [comment]
BTW: I tested this feature and it works well, thanks :).
