### ISSUE TITLE
Check if generated map file is within size range

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/mapsforge-creator#7]
As mentioned by Ludwig [here](https://groups.google.com/d/msg/mapsforge-dev/AHl1lRpFRCg/aMtVGIZiBAAJ):
The size check before overwriting was also useful.

The idea is to check the size of the newly generated map compared to the old map. If the new file is smaller by e.g. 10% we would thrown an error.

**Comment by devemux86** [comment]
Bash can probably provide such functionality.

**Comment by devemux86** [comment]
Creator builds maps without automatically overwriting old ones.
Then checks if new size < 70% old size to reject or keep them.
